if(MULTIPLAYER_GEM_ENABLED)
    set(FILES
        Include/PhysicsGrab/PhysicsGrabComponentBus.h
        Include/PhysicsGrab/PhysicsGrabBus.h
        Include/PhysicsGrab/PhysicsGrabTypeIds.h
        Include/PhysicsGrab/NetworkPhysicsGrabBus.h
        Include/PhysicsGrab/NetworkPhysicsGrabComponentBus.h
    )
else()
    set(FILES
        Include/PhysicsGrab/PhysicsGrabComponentBus.h
        Include/PhysicsGrab/PhysicsGrabBus.h
        Include/PhysicsGrab/PhysicsGrabTypeIds.h
    )
endif()
